#高德地图
amap-maps:
  transport: stdio
  args: [ "-y", "@amap/amap-maps-mcp-server" ]
  command: npx
  env:
    AMAP_MAPS_API_KEY: "Your_AMAP_MAPS_API_KEY"

#12306车票查询
12306-mcp:
  transport: stdio
  args: [ "-y", "12306-mcp" ]
  command: npx

#fetch网页抓取
#fetch:
#  transport: stdio
#  args: [ mcp-server-fetch ]
#  command: uvx


#web搜素
#web-search:
#  transport: sse
#  url: "https://open.bigmodel.cn/api/mcp-broker/proxy/web-search/sse"
#  headers:
#    Authorization: "Your_Zhipu_API_Key"

